// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnLJ-3pCTSxG6uuHwTAL0if4UbopEYsf0',
    appId: '1:735238638391:web:73605658e3b27ce73128b2',
    messagingSenderId: '735238638391',
    projectId: 'instagram-clone-riverpod-15090',
    authDomain: 'instagram-clone-riverpod-15090.firebaseapp.com',
    storageBucket: 'instagram-clone-riverpod-15090.appspot.com',
    measurementId: 'G-4PFF9PDDSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqIAOef9RVYwSoYj6kOXYoGpbU-3pQFWk',
    appId: '1:735238638391:android:b4c0945859fa00933128b2',
    messagingSenderId: '735238638391',
    projectId: 'instagram-clone-riverpod-15090',
    storageBucket: 'instagram-clone-riverpod-15090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPWFEQAm7lwiIuoDhCrz-qGteEOXDs4P4',
    appId: '1:735238638391:ios:075adb7d5bb2c4f63128b2',
    messagingSenderId: '735238638391',
    projectId: 'instagram-clone-riverpod-15090',
    storageBucket: 'instagram-clone-riverpod-15090.appspot.com',
    iosBundleId: 'com.example.flutterNewInstagramCloneFirebaseRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPWFEQAm7lwiIuoDhCrz-qGteEOXDs4P4',
    appId: '1:735238638391:ios:bd04057078b6288e3128b2',
    messagingSenderId: '735238638391',
    projectId: 'instagram-clone-riverpod-15090',
    storageBucket: 'instagram-clone-riverpod-15090.appspot.com',
    iosBundleId: 'com.example.flutterNewInstagramCloneFirebaseRiverpod.RunnerTests',
  );
}
